#uv add    torch

In [3]:
print("yolo")

yolo


In [18]:
import torch

In [26]:
tensor0d = torch.tensor(1)
tensor1d = torch.tensor([1, 2, 3])
tensor2d = torch.tensor([[1, 2], 
                          [3, 4]])
tensor3d = torch.tensor([[[1, 2],[3, 4]],
                          [[5, 6], [7, 8]]])

In [28]:
print(tensor0d)
print(tensor1d.dtype)
print(tensor2d)
print(tensor3d)

tensor(1)
torch.int64
tensor([[1, 2],
        [3, 4]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [29]:
floatvec = torch.tensor([1.0, 2.0, 3.0])
print(floatvec.dtype)

torch.float32


In [31]:
print(tensor1d.dtype)
print(tensor1d)
floatvec = tensor1d.to(torch.float32)
print(floatvec.dtype)
print(floatvec)

torch.int64
tensor([1, 2, 3])
torch.float32
tensor([1., 2., 3.])


In [34]:
tensor2d = torch.tensor([[1, 2, 3], 
                          [4, 5, 6]])
print(tensor2d)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [35]:
print(tensor2d.shape)

torch.Size([2, 3])


In [36]:
print(tensor2d.reshape(3,2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [38]:
print(tensor2d)
print(tensor2d.T)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [39]:
print(tensor2d.matmul(tensor2d.T))

tensor([[14, 32],
        [32, 77]])


In [40]:
tensoreasy = torch.tensor([[1,2],[3,4]])

In [46]:
tensoreasy = torch.tensor([[1,2],[3,4]])
tensoreasy2 = torch.tensor([[5,6],[7,8]])

print(tensoreasy)
print(tensoreasy.T)

print(tensoreasy.matmul(tensoreasy2))

tensor([[1, 2],
        [3, 4]])
tensor([[1, 3],
        [2, 4]])
tensor([[19, 22],
        [43, 50]])
